apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sync2kafka.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sync2kafka.name" . }}
    helm.sh/chart: {{ include "sync2kafka.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  token: {{ .Values.token |b64enc |quote }}
  httpToken: {{ .Values.httpToken |b64enc |quote }}
