apiVersion: v1
kind: Service
metadata:
  name: {{ include "sync2kafka.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sync2kafka.name" . }}
    helm.sh/chart: {{ include "sync2kafka.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9084
      name: sync
{{- if .tlsSecret }}
    - port: 443
      name: https
{{- else }}
    - port: 80
      name: http
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "sync2kafka.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
